"""init

Revision ID: 5501201e5e8c
Revises: 
Create Date: 2024-01-13 11:22:35.599517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5501201e5e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('class_id', sa.CHAR(length=10), nullable=False),
    sa.Column('class_study_program', sa.Enum('TMJ', 'TMD', 'TI', 'TKJ', name='studyprogram'), nullable=False),
    sa.Column('class_major', sa.Enum('TIK', 'TE', 'TGP', 'TM', 'TS', name='major'), nullable=False),
    sa.Column('class_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('room',
    sa.Column('room_id', sa.String(length=10), nullable=False),
    sa.Column('room_building', sa.Enum('GSG', 'AA', name='roombuilding'), nullable=False),
    sa.Column('room_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=18), nullable=False),
    sa.Column('user_role', sa.Enum('ADMIN', 'LECTURER', 'STUDENT', name='rolename'), nullable=False),
    sa.Column('user_fullname', sa.String(length=200), nullable=False),
    sa.Column('user_password_hash', sa.String(length=256), nullable=False),
    sa.Column('user_rfid_hash', sa.String(length=256), nullable=False),
    sa.Column('user_email_address', sa.String(length=100), nullable=False),
    sa.Column('user_home_address', sa.String(length=256), nullable=True),
    sa.Column('lecturer_major', sa.Enum('TIK', 'TE', 'TGP', 'TM', 'TS', name='major'), nullable=True),
    sa.Column('student_class', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['student_class'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email_address'),
    sa.UniqueConstraint('user_rfid_hash')
    )
    op.create_table('course',
    sa.Column('course_id', sa.CHAR(length=15), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_sks', sa.Integer(), nullable=False),
    sa.Column('at_semester', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=9), nullable=False),
    sa.Column('time_start', sa.Time(timezone=True), nullable=False),
    sa.Column('time_end', sa.Time(timezone=True), nullable=False),
    sa.Column('course_description', sa.Text(), nullable=True),
    sa.Column('lecturer_nip', sa.String(length=18), nullable=False),
    sa.Column('class_id', sa.CHAR(length=10), nullable=False),
    sa.Column('room_id', sa.CHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['lecturer_nip'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('lecturer_attendance_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'ALPHA', name='attendancestatus'), nullable=False),
    sa.Column('lecturer_nip', sa.String(length=18), nullable=False),
    sa.Column('course_id', sa.CHAR(length=15), nullable=False),
    sa.Column('room_id', sa.CHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['lecturer_nip'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('student_attendance_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'ALPHA', name='attendancestatus'), nullable=False),
    sa.Column('student_nim', sa.String(length=18), nullable=False),
    sa.Column('course_id', sa.CHAR(length=15), nullable=False),
    sa.Column('room_id', sa.CHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['student_nim'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendance_logs')
    op.drop_table('lecturer_attendance_logs')
    op.drop_table('course')
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('class')
    # ### end Alembic commands ###
