"""update not null constraint on UserTable.user_rfid_hash

Revision ID: 6622af62c35c
Revises: 
Create Date: 2023-12-25 23:30:16.132736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6622af62c35c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tbl', schema=None) as batch_op:
        batch_op.alter_column('user_rfid_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tbl', schema=None) as batch_op:
        batch_op.alter_column('user_rfid_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
